var Config = Config || {};
Config.Language = Config.Language || {};

Config.Language.en =  {
    SelectMake: "Make"
    , SelectModel: "Model"
    , SelectYearModel: "Year model"
    , SelectFuel: "Fuel type"
    , AppoinmentRequest: "Appointment request"
    , RequestedServices: "Requested services"
    , Comments: "Comments"
    , AccountDetail: "Account detail"
    , 'my-tractor-front': "My equipment"
    , 'my-motorbike-front': "My motorbikes"
    , 'my-truck-front': "My trucks"
    , 'my-automobile': "My cars"
    , 'Insert-tractor-front': "Insert equipment"
    , 'Insert-motorbike-front': "Insert motorbike"
    , 'Insert-truck-front': "Insert trucks"
    , 'Insert-automobile': "Insert car"
    , ContactInformation: "Contact information"
    , AppointmentInformation: "Appointment information"
    , ServiceInformation: "Service information"
    , Gasoline: "Gasoline"
    , Diesel: "Diesel"
    , CNG: "CNG"
    , Electric: "Electric"
    , Hybrid: "Hybrid"
    , SpecialOffers: "Special offers"
    , Location: "Dealer location"
    , Appointments: "Appointments"
    , Parts: "Parts"
    , Inventory: "Inventory"
    , Messages: "Messages"
    , Contacts: "Contacts"
    , MyAccount: "My Account"
    , Tools: "Tools"
    , Cargando: "Loading..."
    , DESARROLLADORWEB: "WEB DEVELOPER"
    , DESARROLLADORDWM: "DWM DEVELOPER"
    , Direccion: "Location"
    , Telefono: "Phone"
    , Messages: "Messages"
    , Turnos: "Appointments"
    , Inventary: "Inventory"
    , NEW: "New"
    , USED: "Used"
    , Vehicleinformation: "Vehicle information"
    , Price: "Price"
    , Mileage: "Mileage"
    , Fuel: "Fuel"
    , Color: "Color"
    , Optionals: "Optionals"
    , traction: "Traction"
    , News: "News"
    , Notifications: "Notifications"
    , Terms: "Terms"
    , MyCars: "My Cars"
    , CurrentAccount: "Current account"
    , EnableAppointmentsNotification: "Enable service appointments notifications"
    , EnableServicesNotification: "Enable service notifications"
    , EnableOffersNotification: "Enable offers notifications"
    , EnableMessagesNotification: "Enable messages notifications"
    , MyData: "Profile"
    , Signoff: "Log out"
    , Date: "Date"
    , Receipt: "Receipt"
    , Debit: "Debit"
    , Credit: "Credit"
    , Balance: "Balance"
    , Headline: "Headline"
    , Dealer: "Dealer"
    , Offers: "Offers"
    , Save: "Save"
    , Surname: "Last name"
    , Surename: "Last name"
    , Name: "Name"
    , Model: "Model"
    , HoursUsed: "Hours of use"
    , Fuel: "Fuel"
    , PriceFrom: "Price from"
    , To: "To"
    , SearchingOffers : "Searching offer information"
    , YearFrom: "Year from"
    , Search: "Search"
    , Brand: "Make"
    , Car: "Car"
    , LicensePlate: "License plate"
    , Patent: "License plate"
    , Year: "Year model"
    , ServiceRequired: "Service required"
    , Send: "Send"
    , ServiceHistory: "Service history"
    , Mileage: "Mileage"
    , Results: " Results"
    , Insert: "Insert"
    , Edit: "Edit"
    , Delete: "Delete"
    , Make: "Make"
    , From: "From"
    , AreYouSureYouWantToExit: "Are you certain you want to close the app?"
    , Yes: "Yes"
    , No: "No"
    , ExitApp: "Exit"
    , arriveTo: "Select the store you want to arrive at"
    , DeleteThis: "Are you sure you want to delete this vehicle?"
    , RecordedData: "The data was saved"
    , NoAccount: "I don't have an account"
    , SignUp: "Register"
    , SignIn: "Login"
    , ReplyPassword: "Retype password"
    , Cancel: "Cancel"
    , AsVisitor: "The use of this app constitutes acceptance of the"
    , checkYourEmail: "A confirmation message was sent to your email. Please check your email in order to confirm your account."
    , SeeTerms: "Terms and Conditions"
    , YouMust: "You must activate your user to access your account"
    , GetStarted: "Get started"
    , turnos: "Appointments"
    , inventory: "Inventory"
    , Store: "Stores"
    , Stores: "Stores"
    , Contact: "Contacts"
    , Login: "Log in"
    , Remember: "Remember"
    , All: "All"
    , starred: "Specials"
    , SeeMore: "More"
    , answer: "Answer"
    , Description: "Description "
    , ID: "Code"
    , origin: "Origin"
    , supplier: "Supplier"
    , previousBalance: "Previous balance"
    , exchangeRate: "Exchange rate"
    , Credit: "Credit"
    , FinalBalance: "Final balance"
    , WorkshopAppointment: "Services appointments"
    , AlertLocalization: "You are here"
    , Conversation: "Conversation"
    , ClearFilter: "Clear filter"
    , chargeTo: "Charge to"
    , unit: "Unit"
    , tothe: "to the"
    , ServicesPerformed: "Services performed"
    , jobs: "Jobs"
    , SearchingMessages: "Searching messages"
    , Store: "Store"
    , Branch: "Store"
    , Categories: "Categories"
    , VehicleDetail: "Vehicle detail"
    , displacement: "Displacement"
    , height: "Height"
    , long: "Long"
    , power: "Power"
    , trunk: "Trunk"
    , weight: "Weight"
    , mileage: "Mileage"
    , fuel: "Fuel"
    , AllModels: "All models"
    , AllBrands: "All makes"
    , Any: " Any fuel "
    , NewAndUsed: ' New and used '
    , Result: " Result :"
    , FindUsOn: "Find us"
    , add: "Add"
    , licensePlate: "License plate"
    , InsertMyCar: "Insert car"
    , EditMyCar: "Edit car"
    , VehicleHistory: "Vehicle history"
    , DeleteMyCar: "Delete car"
    , VehicleHistoryNotAvaiable: "The vehicle history is empty."
    , DetailsHistory: "Vehicle history details"
    , CurrentAccountNotAvaiable: "There are no transactions in your account."
    , Register: "Register"
    , Kms: "MIL"
    , SearchingCurrentAccount: "Searching account information"
    , SearchingVehicleHistory: "Searching vehicle history information"
    , MessageAlert: "Sorry, Internet access is required to access this section"
    , sent: "Sent"
    , Account: "Account"
    , Ammount: "Amount"
    , exchangeRateAbbr: "Ex. rate"
    , FullName: "Full name"
    , Code: "Code"
    , price: "Price"
    , ServiceHistory: "Service history"
    , Required: "Required"
    , RequiredEmail: "The email is required"
    , RequiredPassword: "The password is required"
    , InvalidEmail: "Invalid email"
    , PasswordMustMatch: "Password must match"
    , CodeDescription: "Code / Description"
    , NoMessages: "There are no messages in the inbox"
    , EffectiveThrough: "Valid Until"
    , NoOffersAvailable: "There are no offers available at the time"
    , NoBranchsAvailable: "There is no contact information available"
    , OrderParts: "Order parts"
    , itSends: "Order has been added"
    , CouldNotConnect: "Could not connect to server"
    , GeolocalizacionDisabled: " Your device does not have Internet access"
    , Customer: "Customer"
    , quantity: "Quantity"
    , willbesent: "Your message will be sent when the connection is restored"
    , sentSuccessfully: "Sent successfully"
    , Apoint: "Appointment"
    , Services: "Services"
    , NeedLogued: "You need to be logged in for this operation"
    , PartNotAvaiable: " The part is not available "
    , MyOrders: "My orders"
    , Cart: "My order"
    , Order: "Order"
    , OderNotAvaiable: "There are no orders available."
    , checkyourinternetconnection: "Please check your Internet connection"
    , synchronizing: "Synchronizing ..."
    , Loading: "Loading..."
    , noPartsAvailable: "There are no parts available"
    , SearchingParts: "Searching parts information"
    , IventoryNotAvaiable : "Inventory is not available"
    , SearchingInventory: "Searching inventory information"
    , UnitsnotAvailable :"Units Not Available"
    , MustEnterAtLeast3Characters :"You must input at least 3 characters"
    , WaitForSharing: "Searching for sharing platforms"
    , CreateAccount: "Create account"
    , RegisterLater: "Register later"
    , published : " Published "
    , Offert :"Offer"
    , Contact: "Contacts"
    , Tractor: "Tractor front"
    , TractorDetails: "Tractor details"
    , TractorInformation: "Tractor information"
    , checkTheFields :"Check the fields"
    , attached: "Attached"
    , comments: "Comments"
    , DeviceGeolocalizacionDisabled: "Enable the location service on your device"
    , HasNoClientAssociated: "This account doesn’t have a customer associated to it."
    , enabledAcount: "Enable or disable notifications coming to your cell"
    , findcars: " Find or edit your unit’s information. You can also load a new one."
    , stateAcount: "Check the status of your Current Account."
    , myprofiletext: "Change or add data to your profile for better contact with your dealer"
    , findorders: " Here you will find your part orders."
    , seetherems: "Terms and conditions."


}
