var Config = Config || {};
Config.Language = Config.Language || {};

Config.Language["pt-BR"] = {
      SelectMake: "Marca"
    , SelectModel: "Modelo"
    , SelectYearModel: "Ano do modelo"
    , SelectFuel: "Tipo de combustível"
    , AppoinmentRequest: "Agendamento de serviços"
    , RequestedServices: "Serviços Solicitados"
    , Comments: "Comentário"
    , AccountDetail: "Detalhes da conta"
    , 'my-tractor-front': "Minhas máquinas"
    , 'my-motorbike-front': "Mis Motos"
    , 'my-truck-front': "Mis Camiones"
    , 'my-automobile': "Meus Veículos"
    , 'Insert-tractor-front': "Adicionar máquinas"
    , 'Insert-motorbike-front': "Añdir Moto"
    , 'Insert-truck-front': "Añdir Camione"
    , 'Insert-automobile': "Añadir VehÃculo"
    , ContactInformation: "Informações de contato"
    , AppointmentInformation: "Informações de compromisso"
    , ServiceInformation: "Informações de serviço"
    , Gasoline: "Nafta"
    , Diesel: "Diesel"
    , CNG: "GNC"
    , Electric: "Elétrico"
    , Hybrid: "Híbrido"
    , SpecialOffers: "Ofertas Especiais"
    , Location: "Localização "
    , Appointments: "Agendamento de serviços"
    , Parts: "Peças"
    , Inventory: "Unidades disponíveis"
    , Messages: "Mensagens"
    , Contacts: "Contatos"
    , MyAccount: "Minha Conta"
    , Tools: "Ferramentas"
    , Cargando: "Carregando..."
    , DESARROLLADORWEB: "DESARROLLADOR WEB"
    , DESARROLLADORDWM: "DESARROLLADOR DWM"
    , Direccion: "Endereço"
    , Telefono: "Telefone"
    , Messages: "Mensagens"
    , Turnos: "Agendamento de serviços"
    , Inventary: "Veículos"
    , NEW: "Novos"
    , USED: "Usados"
    , Vehicleinformation: "Informação do veículo"
    , Price: "Precio"
    , Mileage: "Km"
    , Fuel: "Combustível"
    , Color: "Cor"
    , Optionals: "Opcionais"
    , traction: "Tração"
    , News: "Notícias"
    , Notifications: "Notificações"
    , Terms: "Termos e Condições"
    , MyCars: "Mis Veículos"
    , CurrentAccount: "Conta Correntee"
    , EnableAppointmentsNotification: "Activar notificaciones de turnos de taller"
    , EnableServicesNotification: "Activar notificaciones de servicios"
    , EnableOffersNotification: "Activar notificaciones de ofertas"
    , EnableMessagesNotification: "Activar notificaciones de mensajes"
    , MyData: "Meu Perfil"
    , Signoff: "Sair"
    , Date: "Data"
    , Receipt: "Comprovante"
    , Debit: "Débito"
    , Credit: "Crédito"
    , Balance: "Saldo"
    , Headline: "Titular"
    , Dealer: "Concessionário"
    , Offers: "Ofertas"
    , Save: "Guardar"
    , Surname: "Sobrenome"
    , Surename: "Sobrenome"
    , Name: "Nome"
    , Model: "Modelo"
    , HoursUsed: "Horas de uso"
    , Fuel: "combustível"
    , PriceFrom: "Precio de"
    , To: "Até"
    , SearchingOffers : "Buscando ofertas"
    , YearFrom: "Ano de"
    , Search: "Pesquisar"
    , Brand: "Marca"
    , Car: "Veículos"
    , LicensePlate: "Patente"
    , Patent: "Patente"
    , Year: "Ano"
    , ServiceRequired: "Servicio Requerido"
    , Send: "Enviar"
    , ServiceHistory: "Historial de Servicio"
    , Mileage: "Kilometraje"
    , Results: " Resultados"
    , Insert: "Alta"
    , Edit: "Editar"
    , Delete: "Borrar"
    , Make: "Marca"
    , From: "De"
    , AreYouSureYouWantToExit: "¿Está seguro que desea salir de la aplicación?"
    , Yes: "Sí"
    , No: "No"
    , ExitApp: "Salir de la aplicación"
    , arriveTo: "Escolha uma filial"
    , DeleteThis: "Â¿EstÃ¡ seguro que desea eliminar este vehÃculo?"
    , RecordedData: "Se han grabado los datos"
    , NoAccount: "No tengo conta"
    , SignUn: "Criar Conta"
    , SignIn: "Entrar"
    , ReplyPassword: "Reentrar password"
    , Cancel: "Cancelar"
    , AsVisitor: "El uso de esta aplicación asume la aceptación de los"
    , checkYourEmail: "Un mail de confirmaciÃ³n fue enviado. Por favor revise su correo para poder activar su cuenta."
    , SeeTerms: "Termos e Condições"
    , YouMust: "Debe activar la cuenta de usuario por favor confirme el correo que le enviamos"
    , GetStarted: "Começar"
    , turnos: "Agendamento de serviços"
    , inventory: "Unidades disponíveis"
    , Branch: "Filial"
    , Store: "Filial"
    , Stores: "Filiais"
    , Contact: "Contatos"
    , Login: "Entrar"
    , Remember: "Recordarme en este Equipo"
    , All: "Todos"
    , starred: "Destacados"
    , SeeMore: "Veja mais"
    , answer: "Responder"
    , Description: "Descrição"
    , ID: "CÃ³digo "
    , origin: "Origen"
    , supplier: "Proveedor"
    , previousBalance: "Balance Anterior"
    , exchangeRate: "Tipo de Cambio"
    , FinalBalance: "Saldo Final "
    , WorkshopAppointment: "Turno de taller"
    , AlertLocalization: "Você está aqui"
    , Conversation: "Conversaciones"
    , ClearFilter: "Borrar Filtro"
    , chargeTo: "Para Cobrar"
    , unit: "Unidad"
    , tothe: "a los"
    , ServicesPerformed: "Servicios Realizados"
    , jobs: "Trabajos"
    , SearchingMessages: "Buscando mensajes"
    , Categories: "Categorias"
    , VehicleDetail: "Detalhe do veículo"
    , displacement: "Cilindrada"
    , height: "Altura"
    , long: "Largo"
    , power: "Potencia"
    , trunk: "BaÃºl"
    , weight: "Ancho"
    , mileage: "Km"
    , fuel: "Combustible"
    , AllModels: " Todos os Modelos "
    , AllBrands: " Todas as Marcas "
    , Any: " Cualquer "
    , NewAndUsed: ' Novas e Usadas '
    , Result: " Resultado"
    , FindUsOn: "Pode encontrar-nos"
    , add: "Adicionar"
    , licensePlate: "Patente"
    , InsertMyCar: "Adicionar Vehículo"
    , EditMyCar: "Editar Veículo"
    , VehicleHistory: "Historial de Servicio"
    , DeleteMyCar: "Eliminar Veículo"
    , VehicleHistoryNotAvaiable: "Historial de Servicio no disponible."
    , DetailsHistory: "Detalle del Historial"
    , CurrentAccountNotAvaiable: "No hay movimientos en su cuenta corriente."
    , Register: "Registro"
    , Kms: "Kms"
    , SearchingCurrentAccount: "Buscando cuenta corriente"
    , SearchingVehicleHistory: "Buscando historial de servicio"
    , MessageAlert: "Lo sentimos pero esta secciÃ³n requiere de acceso a Internet."
    , sent: "Enviado "
    , Account: "Conta"
    , Ammount: "Monto"
    , exchangeRateAbbr: "T. de Cambio"
    , FullName: "Nome Completo"
    , Code: "CÃ³digo"
    , price: "Precio"
    , ServiceMaked: "Servicios Realizados"
    , Required: "Requerido"
    , InvalidEmail: "Email InvÃ¡lido"
    , RequiredEmail: "El email es requerido"
    , RequiredPassword: "El password es requerido"
    , PasswordMustMatch: "Deben Coincidir"
    , CodeDescription: "código ou descrição"
    , NoMessages: "Não há mensagens na caixa de entrada"
    , EffectiveThrough: "válido até"
    , NoOffersAvailable: "Não há promoções"
    , NoBranchsAvailable: "No hay datos de contacto disponibles"
    , OrderParts: "Pedido de Repuesto"
    , itSends: "Se ha agregago a la lista de  pedidos"
    , CouldNotConnect: "No se pudo conectar al servidor"
    , GeolocalizacionDisabled: " Su dispositivo no tiene acceso a Internet"
    , Customer: "Cliente"
    , quantity: "Cantidad"
    , willbesent: "Su mensaje serÃ¡  enviado cuando se reestablezca la conecciÃ³n"
    , sentSuccessfully: "Enviado Correctamente"
    , Apoint: "Turno"
    , Services: "Servicio"
    , NeedLogued: "necesitas autenticacion para realizar esta operacion"
    , PartNotAvaiable: "El repuesto no se encuentra disponible"
    , MyOrders: "Solicitudes de Repuestos"
    , Cart: "Mi Pedido"
    , Order: "Pedido"
    , OderNotAvaiable: "No hay Pedidos Disponibles."
    , checkyourinternetconnection: "verifica coneccion a internet "
    , synchronizing: "sincronizando ..."
    , Loading:"Cargando..."
    , noPartsAvailable :"No Hay Repuestos Disponibles"
    , SearchingParts: "Buscando respuestos"
    , IventoryNotAvaiable : "Unidades no disponibles"
    , SearchingInventory: "Buscando en el inventario"
    , UnitsnotAvailable : "No Tiene Unidades Disponibles "
    , MustEnterAtLeast3Characters :"debe ingresar al menos 3 caracteres"
    , WaitForSharing: "Buscando aplicaciones para compartir"
    , CreateAccount: "Crear cuenta"
    , RegisterLater: "Registrarme luego"
    , published : " Publicado "
    , Offert :"Oferta"
    , Contact: "Contatos"
    , Tractor: "Máquinas"
    , TractorDetails: "Detalhe das Máquias"
    , TractorInformation: "Informações das Máquinas"
    , checkTheFields: "Verifique los Campos"
}
